### ISSUE TITLE
graf in tabela

### ISSUE THREAD

**Issue by zantavcar** [zantavcar/APPR-2015-16#3]
zanima me, kako bi na enostaven način iz tabele tidy_Prosnje2015 naredil graf o dinamiki prošenj za azil to leto za različne države (npr. za Nemčijo, Avstrijo, Švedsko,Italijo,Francijo...), ter da bi to združil na en graf.

namen imam še uvoziti tabelo o številu prebivalcev EU držav in me zanima, kako bi lahko to združil s prvotno tidy_Prosnje2015 ter imel poračunane prošnje za azil na milijon prebivalcev, kar bi kasneje uporabil za zemljevid.

Za odgovor se vnaprej zahvaljujem, lp Žan

**Comment by jaanos** [comment]
Graf lahko narediš nekako takole:

``` R
ggplot(tidy_Prosnje2015 %>% filter(ASYL_APP == "Asylum applicant",
                                   GEO %in% c("Germany", "Austria", "Sweden", "Italy", "France")),
       aes(x = TIME, y = Value, group = GEO, color = GEO)) + geom_line()
```

Kar se združevanja razpredelnic tiče, bo to najlažje narediti s funkcijo `inner_join` (po potrebi lahko razpredelnice predhodno filtriraš), potem pa z `mutate` izračunaš povprečje. Če bi imel npr. razpredelnico `prebivalstvo.EU` s stolpcema `drzava` in `prebivalstvo`, bi lahko naredil nekaj takega:

``` R
povprecja <- inner_join(tidy_Prosnje2015, prebvalstvo.EU,
                        by = c("GEO" = "drzava")) %>%
  mutate(povprecje = Value/prebivalstvo)
```

**Comment by zantavcar** [comment]
hvala za pomoč in hiter odgovor,

lep pozdrav, žan
